language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
install:
  - npm install
script:
  - npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
